name: Tests
on: [push]
jobs:
  build-test-lint-typecheck-e2e:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # If you're using actions/checkout@v2 you must set persist-credentials to false in most cases for the deployment to work correctly.
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "14"
      - name: Cypress install
        uses: cypress-io/github-action@v4
        with:
          runTests: false
      # report machine parameters
      - run: yarn cypress info
      - run: node --version
      - run: node -p 'os.cpus()'
      - run: yarn types
      - run: yarn test:unit:ci
      - run: yarn build:ci
        # the entire command will automatically be prefixed with "npm"
        # and we need the second "npm" to execute "cypress run ..." command line.
      - name: Percy Test
        run: npx percy exec -- cypress run --component
        env:
          PERCY_TOKEN: 9c1697c92b9c851f162d9bb12e08eddd25f9d7fc075a36fa28c73ab54c39e797
